//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionDemo_II.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stu
    {
        public string professional { get; set; }
        public string stuid { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public string nationality { get; set; }
        public string number { get; set; }
        public string InternshipType { get; set; }
        public string InternshipLocation { get; set; }
        public string money { get; set; }
        public string accommodation { get; set; }
        public string msg { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
